apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
  labels:
    app: kubia-b
spec:
  selector:
    matchLabels:
      app: kubia-b
  template:
    metadata:
      labels:
        app: kubia-b
    spec:
      containers:
      - name: kubia-cnt
        image: terezabisharyan/kubia
        ports:
        - containerPort: 80
